imports:
    - { resource: parameters.ini }
    - { resource: local_parameters.yml, ignore_errors: true }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          '%secret%'
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    translator:      { fallback: en }
    session:
        default_locale: '%locale%'
        auto_start:     true

# Twig Configuration
twig:
    debug:            '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Assetic Configuration
assetic:
    debug:          '%kernel.debug%'
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:         %database_driver%
        host:           %database_host%
        dbname:         %database_name%
        user:           %database_user%
        password:       %database_password%
        unix_socket:    %database_socket%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host:      '%mailer_host%'
    username:  '%mailer_user%'
    password:  '%mailer_password%'

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false
    
stfalcon_tinymce:
    theme:
      advanced: 
        width: '100%'
        theme: "advanced"
        theme_advanced_buttons1: "mylistbox,mysplitbutton,bold,italic,underline,separator,strikethrough,justifyleft,justifycenter,justifyright,justifyfull,bullist,numlist,undo,redo,link,unlink"
        theme_advanced_buttons2: ""
        theme_advanced_buttons3: ""
        theme_advanced_toolbar_location: "top"
        theme_advanced_toolbar_align: "left"
        theme_advanced_statusbar_location: "bottom"
        plugins: "fullscreen, pagebreak"
        theme_advanced_buttons1_add: "pagebreak,fullscreen,code"
        theme_advanced_resizing: true
        extended_valid_elements : "textarea[cols|rows|disabled|name|readonly|class],pre[name]" 
        remove_linebreaks: false
        preformatted : true
        pagebreak_separator: "<!-- more -->"
        force_br_newlines: false
        apply_source_formatting: true
        verify_html: false

wowbile_frontend:
    site_name: wöwbile
    twitter: wowbile
    
kailab_shared:
    mobile_version: Wowbile\Bundle\MobileBundle

