
homepage:
    pattern:  /
    defaults: { _controller: "WowbileFrontendBundle:Default:index" }
    
mobile_homepage:
    pattern:  /m
    defaults: { _controller: "WowbileMobileBundle:Default:index" }
    

WowbileMobileBundle:
    resource: "@WowbileMobileBundle/Controller/"
    type:     annotation
    prefix:   /m

localized_homepage:
    pattern:  /{_locale}
    defaults: { _controller: "WowbileFrontendBundle:Default:index" }
    requirements:
        _locale: ^..$
    
backend:
    prefix:   /admin
    resource: "@WowbileBackendBundle/Resources/config/routing.yml"
    
WowbileBackendBundle:
    resource: "@WowbileBackendBundle/Controller/"
    type:     annotation
    prefix:   /admin

WowbileFrontendBundle:
    resource: "@WowbileFrontendBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale: ^..$ 

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
