
homepage:
    pattern:  /
    defaults: { _controller: "WowbileFrontendBundle:Default:index" }
    
mobile_homepage:
    pattern:  /m
    defaults: { _controller: "WowbileMobileBundle:Default:index" }
    
backend:
    prefix:   /admin
    resource: "@WowbileBackendBundle/Resources/config/routing.yml"

WowbileMobileBundle:
    resource: "@WowbileMobileBundle/Controller/"
    type:     annotation
    prefix:   /m
    
WowbileBackendBundle:
    resource: "@WowbileBackendBundle/Controller/"
    type:     annotation
    prefix:   /admin

WowbileFrontendBundle:
    resource: "@WowbileFrontendBundle/Controller/"
    type:     annotation